theme: jekyll-theme-minimal

title: Wisconsin Autonomous
description: Wisconsin Autonomous is a student organization at the University of Wisconsin - Madison.
logo: https://github.com/WisconsinAutonomous/wa-resources/blob/master/Images/WA.png?raw=true
